size_channels: 4
size_bandwidth: 24
lrf_bandwidths: [24, 24, 24, 24, 24]
lrf_features: [4, 40, 20, 10, 1]
augmentation: 1
leaf_sub_sampling: 0.0
leaf_keypoints: 0.015
radius_descriptor: 0.015
epochs_max: 80
learning_rate: 0.001
ext: 'ply'
size_pcd: 1225
step_per_save: 500
step_per_viz: 25
name_data_set: StanfordViews
removal_augmentation: 1
